// <auto-generated />
using System;
using DongonResidentialsRental.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DongonResidentialsRental.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260404221920_AddedForeignKeysToTablesAccordingly")]
    partial class AddedForeignKeysToTablesAccordingly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DongonResidentialsRental.Domain.Building.Building", b =>
                {
                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.HasKey("BuildingId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("buildings", (string)null);
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.CreditNote.CreditAllocation", b =>
                {
                    b.Property<Guid>("CreditAllocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("credit_allocation_id");

                    b.Property<DateOnly>("AppliedOn")
                        .HasColumnType("date")
                        .HasColumnName("applied_on");

                    b.Property<Guid>("CreditNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("credit_note_id");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.HasKey("CreditAllocationId");

                    b.HasIndex("CreditNoteId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("credit_allocations", (string)null);
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.CreditNote.CreditNote", b =>
                {
                    b.Property<Guid>("CreditNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("credit_note_id");

                    b.Property<DateOnly?>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("CreditNoteId");

                    b.HasIndex("IssuedOn");

                    b.HasIndex("LeaseId");

                    b.HasIndex("Status");

                    b.ToTable("credit_notes", (string)null);
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Invoice.Invoice", b =>
                {
                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("invoice_number");

                    b.Property<DateOnly?>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("InvoiceId");

                    b.HasIndex("DueDate");

                    b.HasIndex("InvoiceNumber")
                        .IsUnique();

                    b.HasIndex("IssuedOn");

                    b.HasIndex("LeaseId");

                    b.HasIndex("Status");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Invoice.InvoiceAllocation", b =>
                {
                    b.Property<Guid>("InvoiceAllocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_allocation_id");

                    b.Property<DateOnly>("AppliedOn")
                        .HasColumnType("date")
                        .HasColumnName("applied_on");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.HasKey("InvoiceAllocationId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentId");

                    b.ToTable("invoice_allocations", (string)null);
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Invoice.InvoiceCreditAllocation", b =>
                {
                    b.Property<Guid>("InvoiceCreditAllocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_credit_allocation_id");

                    b.Property<DateOnly>("AppliedOn")
                        .HasColumnType("date")
                        .HasColumnName("applied_on");

                    b.Property<Guid>("CreditNoteId")
                        .HasColumnType("uuid")
                        .HasColumnName("credit_note_id");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.HasKey("InvoiceCreditAllocationId");

                    b.HasIndex("CreditNoteId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_credit_allocations", (string)null);
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Invoice.InvoiceLine", b =>
                {
                    b.Property<Guid>("InvoiceLineId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_line_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("description");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("InvoiceLineId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_lines", (string)null);
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Lease.Lease", b =>
                {
                    b.Property<Guid>("LeaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("lease_id");

                    b.Property<Guid>("Occupancy")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.HasKey("LeaseId");

                    b.HasIndex("Occupancy");

                    b.HasIndex("Status");

                    b.HasIndex("UnitId");

                    b.ToTable("leases", (string)null);
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Payment.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("method");

                    b.Property<DateOnly>("ReceivedOn")
                        .HasColumnType("date")
                        .HasColumnName("received_on");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<string>("ReversalReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reversal_reason");

                    b.Property<DateOnly?>("ReversedOn")
                        .HasColumnType("date")
                        .HasColumnName("reversed_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("PaymentId");

                    b.HasIndex("Method");

                    b.HasIndex("ReceivedOn");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.ToTable("payments", (string)null);
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Payment.PaymentAllocation", b =>
                {
                    b.Property<Guid>("PaymentAllocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_allocation_id");

                    b.Property<DateOnly>("AllocatedOn")
                        .HasColumnType("date")
                        .HasColumnName("allocated_on");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("payment_id");

                    b.HasKey("PaymentAllocationId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("PaymentId");

                    b.ToTable("payment_allocations", (string)null);
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Tenant.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("TenantId");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Unit.Unit", b =>
                {
                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uuid")
                        .HasColumnName("building_id");

                    b.Property<int?>("Floor")
                        .HasColumnType("integer")
                        .HasColumnName("floor");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("UnitNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("unit_number");

                    b.HasKey("UnitId");

                    b.HasIndex("BuildingId", "UnitNumber")
                        .IsUnique();

                    b.ToTable("units", (string)null);
                });

            modelBuilder.Entity("DongonResidentialsRental.Persistence.Models.InvoiceSequence", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.Property<int>("LastNumber")
                        .HasColumnType("integer")
                        .HasColumnName("last_number");

                    b.HasKey("Year");

                    b.ToTable("invoice_sequences", (string)null);
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Building.Building", b =>
                {
                    b.OwnsOne("DongonResidentialsRental.Domain.Shared.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("BuildingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("city");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("Province")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("province");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("street");

                            b1.HasKey("BuildingId");

                            b1.ToTable("buildings");

                            b1.WithOwner()
                                .HasForeignKey("BuildingId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.CreditNote.CreditAllocation", b =>
                {
                    b.HasOne("DongonResidentialsRental.Domain.CreditNote.CreditNote", null)
                        .WithMany("Allocations")
                        .HasForeignKey("CreditNoteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DongonResidentialsRental.Domain.Invoice.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DongonResidentialsRental.Domain.Shared.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("CreditAllocationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency");

                            b1.HasKey("CreditAllocationId");

                            b1.ToTable("credit_allocations");

                            b1.WithOwner()
                                .HasForeignKey("CreditAllocationId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.CreditNote.CreditNote", b =>
                {
                    b.HasOne("DongonResidentialsRental.Domain.Lease.Lease", null)
                        .WithMany()
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DongonResidentialsRental.Domain.Shared.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("CreditNoteId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency");

                            b1.HasKey("CreditNoteId");

                            b1.ToTable("credit_notes");

                            b1.WithOwner()
                                .HasForeignKey("CreditNoteId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Invoice.Invoice", b =>
                {
                    b.HasOne("DongonResidentialsRental.Domain.Lease.Lease", null)
                        .WithMany()
                        .HasForeignKey("LeaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DongonResidentialsRental.Domain.Invoice.BillingPeriod", "BillingPeriod", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("From")
                                .HasColumnType("date")
                                .HasColumnName("from");

                            b1.Property<DateOnly>("To")
                                .HasColumnType("date")
                                .HasColumnName("to");

                            b1.HasKey("InvoiceId");

                            b1.HasIndex("From", "To");

                            b1.ToTable("invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.Navigation("BillingPeriod")
                        .IsRequired();
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Invoice.InvoiceAllocation", b =>
                {
                    b.HasOne("DongonResidentialsRental.Domain.Invoice.Invoice", null)
                        .WithMany("Allocations")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DongonResidentialsRental.Domain.Shared.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("InvoiceAllocationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency");

                            b1.HasKey("InvoiceAllocationId");

                            b1.ToTable("invoice_allocations");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceAllocationId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Invoice.InvoiceCreditAllocation", b =>
                {
                    b.HasOne("DongonResidentialsRental.Domain.Invoice.Invoice", null)
                        .WithMany("CreditAllocations")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DongonResidentialsRental.Domain.Shared.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("InvoiceCreditAllocationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency");

                            b1.HasKey("InvoiceCreditAllocationId");

                            b1.ToTable("invoice_credit_allocations");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceCreditAllocationId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Invoice.InvoiceLine", b =>
                {
                    b.HasOne("DongonResidentialsRental.Domain.Invoice.Invoice", null)
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DongonResidentialsRental.Domain.Shared.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("InvoiceLineId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("unit_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("unit_price_currency");

                            b1.HasKey("InvoiceLineId");

                            b1.ToTable("invoice_lines");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceLineId");
                        });

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Lease.Lease", b =>
                {
                    b.HasOne("DongonResidentialsRental.Domain.Tenant.Tenant", null)
                        .WithMany()
                        .HasForeignKey("Occupancy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DongonResidentialsRental.Domain.Unit.Unit", null)
                        .WithMany()
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DongonResidentialsRental.Domain.Shared.Money", "MonthlyRate", b1 =>
                        {
                            b1.Property<Guid>("LeaseId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("monthly_rate_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("monthly_rate_currency");

                            b1.HasKey("LeaseId");

                            b1.ToTable("leases");

                            b1.WithOwner()
                                .HasForeignKey("LeaseId");
                        });

                    b.OwnsOne("DongonResidentialsRental.Domain.Lease.LeaseTerm", "Term", b1 =>
                        {
                            b1.Property<Guid>("LeaseId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date")
                                .HasColumnName("end_date");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date")
                                .HasColumnName("start_date");

                            b1.HasKey("LeaseId");

                            b1.HasIndex("StartDate", "EndDate");

                            b1.ToTable("leases");

                            b1.WithOwner()
                                .HasForeignKey("LeaseId");
                        });

                    b.OwnsOne("DongonResidentialsRental.Domain.Lease.UtilityResponsibility", "UtilityResponsibility", b1 =>
                        {
                            b1.Property<Guid>("LeaseId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("TenantPaysElectricity")
                                .HasColumnType("boolean")
                                .HasColumnName("tenant_pays_electricity");

                            b1.Property<bool>("TenantPaysWater")
                                .HasColumnType("boolean")
                                .HasColumnName("tenant_pays_water");

                            b1.HasKey("LeaseId");

                            b1.ToTable("leases");

                            b1.WithOwner()
                                .HasForeignKey("LeaseId");
                        });

                    b.OwnsOne("DongonResidentialsRental.Domain.Shared.BillingSettings", "BillingSettings", b1 =>
                        {
                            b1.Property<Guid>("LeaseId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DueDayOfMonth")
                                .HasColumnType("integer")
                                .HasColumnName("due_day_of_month");

                            b1.Property<int>("GracePeriodDays")
                                .HasColumnType("integer")
                                .HasColumnName("grace_period_days");

                            b1.HasKey("LeaseId");

                            b1.ToTable("leases");

                            b1.WithOwner()
                                .HasForeignKey("LeaseId");
                        });

                    b.Navigation("BillingSettings")
                        .IsRequired();

                    b.Navigation("MonthlyRate")
                        .IsRequired();

                    b.Navigation("Term")
                        .IsRequired();

                    b.Navigation("UtilityResponsibility")
                        .IsRequired();
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Payment.Payment", b =>
                {
                    b.HasOne("DongonResidentialsRental.Domain.Tenant.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("DongonResidentialsRental.Domain.Shared.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency");

                            b1.HasKey("PaymentId");

                            b1.ToTable("payments");

                            b1.WithOwner()
                                .HasForeignKey("PaymentId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Payment.PaymentAllocation", b =>
                {
                    b.HasOne("DongonResidentialsRental.Domain.Invoice.Invoice", null)
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DongonResidentialsRental.Domain.Payment.Payment", null)
                        .WithMany("Allocations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DongonResidentialsRental.Domain.Shared.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("PaymentAllocationId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("amount_currency");

                            b1.HasKey("PaymentAllocationId");

                            b1.ToTable("payment_allocations");

                            b1.WithOwner()
                                .HasForeignKey("PaymentAllocationId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Tenant.Tenant", b =>
                {
                    b.OwnsOne("DongonResidentialsRental.Domain.Shared.ContactInfo", "ContactInfo", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");

                            b1.OwnsOne("DongonResidentialsRental.Domain.Shared.Email", "Email", b2 =>
                                {
                                    b2.Property<Guid>("ContactInfoTenantId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(255)
                                        .HasColumnType("character varying(255)")
                                        .HasColumnName("email");

                                    b2.HasKey("ContactInfoTenantId");

                                    b2.HasIndex("Value")
                                        .IsUnique();

                                    b2.ToTable("tenants");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoTenantId");
                                });

                            b1.OwnsOne("DongonResidentialsRental.Domain.Shared.PhoneNumber", "PhoneNumber", b2 =>
                                {
                                    b2.Property<Guid>("ContactInfoTenantId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("phone_number");

                                    b2.HasKey("ContactInfoTenantId");

                                    b2.ToTable("tenants");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactInfoTenantId");
                                });

                            b1.Navigation("Email")
                                .IsRequired();

                            b1.Navigation("PhoneNumber")
                                .IsRequired();
                        });

                    b.OwnsOne("DongonResidentialsRental.Domain.Tenant.PersonalInfo", "PersonalInfo", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("PersonalInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Unit.Unit", b =>
                {
                    b.HasOne("DongonResidentialsRental.Domain.Building.Building", null)
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.CreditNote.CreditNote", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Invoice.Invoice", b =>
                {
                    b.Navigation("Allocations");

                    b.Navigation("CreditAllocations");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("DongonResidentialsRental.Domain.Payment.Payment", b =>
                {
                    b.Navigation("Allocations");
                });
#pragma warning restore 612, 618
        }
    }
}
